const caixaPrincipal = document.querySelector(".caixa-pricipal")
const caixaPerguntas = document.querySelector(".caixa-perguntas")
const caixaAlternativas = document.querySelector(".caixa-alternativas")
const caixaResultados = document.querySelector(".caixa-resultados")
const textoPricipal = document.querySelector(".texto-pricipal")